services:
  backend:
    build: ./server
    image: dadandan/project-mark-it-backend
    ports:
      - "3001:3001"
    environment:
      - STRIPE_TEST_SECRET=${STRIPE_TEST_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - CLIPDROP_API_KEY=${CLIPDROP_API_KEY}
      - FRONTEND_DOMAIN=http://${DOMAIN}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - VIRTUAL_PORT=3001
    depends_on:
      - postgres 

  frontend:
    build: .
    image: dadandan/project-mark-it-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - sockets
  
  sockets:
    build: ./sockets
    image: dadandan/project-mark-it-sockets
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    container_name: mark-it-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: